export * from "./schema";
export type {
	Event,
	NewEvent,
	SponsorTier,
	NewSponsorTier,
	Sponsor,
	NewSponsor,
	Speaker,
	NewSpeaker,
	ScheduleSession,
	NewScheduleSession,
	Judge,
	NewJudge,
	Attendee,
	NewAttendee,
	Job,
	NewJob,
	Badge,
	NewBadge,
	HackathonTrack,
	NewHackathonTrack,
	HackathonTeam,
	NewHackathonTeam,
	HackathonSubmission,
	NewHackathonSubmission,
	Mentor,
	NewMentor,
	CommunityPartner,
	NewCommunityPartner,
	Poster,
	NewPoster,
} from "./schema";

export { createDB, type Database } from "./connection";
export {
	createQueries,
	createAttendeeQueries,
	createBadgeQueries,
	createEventQueries,
	createPosterQueries,
} from "./queries";
