const speakers = [
	{
		id: "spk-001",
		name: "Sebastián Torres",
		bio: "Staff Engineer at Vercel. Building the future of edge computing and serverless infrastructure.",
		company: "Vercel",
		title: "Staff Engineer",
		avatar: "https://i.pravatar.cc/150?img=11",
		twitter: "@sebatorres_dev",
		github: "sebatorres",
		topics: ["edge computing", "serverless", "Next.js"],
		city: "Buenos Aires, Argentina",
	},
	{
		id: "spk-002",
		name: "Valentina Ríos",
		bio: "AI researcher and open source advocate. Core contributor to several LLM evaluation frameworks.",
		company: "Hugging Face",
		title: "ML Research Engineer",
		avatar: "https://i.pravatar.cc/150?img=5",
		twitter: "@valrios_ai",
		github: "valrios",
		topics: ["machine learning", "LLMs", "open source"],
		city: "Medellín, Colombia",
	},
	{
		id: "spk-003",
		name: "Daniel Park",
		bio: "Creator of several popular open source dev tools. Passionate about DX and building in public.",
		company: "Independent",
		title: "Open Source Engineer",
		avatar: "https://i.pravatar.cc/150?img=12",
		twitter: "@danielpark_oss",
		github: "danielpark",
		topics: ["developer tools", "open source", "CLI"],
		city: "Lima, Peru",
	},
	{
		id: "spk-004",
		name: "Camila Herrera",
		bio: "Design engineer at Linear. Pushing the boundaries of interface animation and interaction design.",
		company: "Linear",
		title: "Design Engineer",
		avatar: "https://i.pravatar.cc/150?img=9",
		twitter: "@camilaherrera",
		github: "camilaherrera",
		topics: ["design engineering", "animation", "UX"],
		city: "Santiago, Chile",
	},
	{
		id: "spk-005",
		name: "Marcus Webb",
		bio: "Principal engineer at Cloudflare. Architecting distributed systems at planetary scale.",
		company: "Cloudflare",
		title: "Principal Engineer",
		avatar: "https://i.pravatar.cc/150?img=15",
		twitter: "@marcuswebb",
		github: "marcuswebb",
		topics: ["distributed systems", "WebAssembly", "edge networks"],
		city: "Austin, TX",
	},
	{
		id: "spk-006",
		name: "Luciana Campos",
		bio: "CTO and cofounder of a B2B SaaS. Building the next generation of developer collaboration tools.",
		company: "Flowdash",
		title: "CTO & Cofounder",
		avatar: "https://i.pravatar.cc/150?img=44",
		twitter: "@lucianacampos",
		github: "lucianacampos",
		topics: ["startups", "product engineering", "team building"],
		city: "São Paulo, Brazil",
	},
	{
		id: "spk-007",
		name: "Andrés Molina",
		bio: "Rust core contributor and systems programmer. Advocates for memory safety in critical infrastructure.",
		company: "Mozilla",
		title: "Systems Engineer",
		avatar: "https://i.pravatar.cc/150?img=14",
		twitter: "@andresmolina_rs",
		github: "andresmolina",
		topics: ["Rust", "systems programming", "WebAssembly"],
		city: "Bogotá, Colombia",
	},
	{
		id: "spk-008",
		name: "Priya Nair",
		bio: "AI product lead at Anthropic. Bringing safe AI capabilities to production developer workflows.",
		company: "Anthropic",
		title: "AI Product Lead",
		avatar: "https://i.pravatar.cc/150?img=47",
		twitter: "@priyanair_ai",
		github: "priyanair",
		topics: ["AI safety", "AI agents", "developer AI tools"],
		city: "San Francisco, CA",
	},
];

const sponsorTiers = [
	{
		id: "tier-platinum",
		name: "Platinum",
		price: 15000,
		color: "#E5E7EB",
		benefits: [
			"Keynote speaking slot",
			"Premium booth (6x6m)",
			"Logo on all materials",
			"10 attendee passes",
			"1:1 networking session",
			"Workshop slot",
		],
		maxSponsors: 2,
	},
	{
		id: "tier-gold",
		name: "Gold",
		price: 8000,
		color: "#F59E0B",
		benefits: [
			"Panel speaking slot",
			"Standard booth (3x3m)",
			"Logo on website",
			"6 attendee passes",
			"Recruiting table",
		],
		maxSponsors: 4,
	},
	{
		id: "tier-silver",
		name: "Silver",
		price: 3500,
		color: "#6B7280",
		benefits: ["Logo on website", "3 attendee passes", "Social media mention", "Job board listing"],
		maxSponsors: 8,
	},
	{
		id: "tier-community",
		name: "Community",
		price: 1000,
		color: "#10B981",
		benefits: ["Logo on website", "2 attendee passes", "Social media mention"],
		maxSponsors: 12,
	},
];

const sponsors = [
	{
		id: "spo-001",
		name: "Vercel",
		tierId: "tier-platinum",
		logo: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico",
		website: "https://vercel.com",
		description: "The platform for frontend developers.",
		country: "US",
	},
	{
		id: "spo-002",
		name: "Clerk",
		tierId: "tier-platinum",
		logo: "https://clerk.com/favicon.ico",
		website: "https://clerk.com",
		description: "The most comprehensive User Management Platform.",
		country: "US",
	},
	{
		id: "spo-003",
		name: "PlanetScale",
		tierId: "tier-gold",
		logo: "https://planetscale.com/favicon.ico",
		website: "https://planetscale.com",
		description: "The world's most advanced serverless MySQL platform.",
		country: "US",
	},
	{
		id: "spo-004",
		name: "Resend",
		tierId: "tier-gold",
		logo: "https://resend.com/favicon.ico",
		website: "https://resend.com",
		description: "Email for developers.",
		country: "US",
	},
	{
		id: "spo-005",
		name: "Trigger.dev",
		tierId: "tier-gold",
		logo: "https://trigger.dev/favicon.ico",
		website: "https://trigger.dev",
		description: "Open source background jobs for developers.",
		country: "UK",
	},
	{
		id: "spo-006",
		name: "Neon",
		tierId: "tier-gold",
		logo: "https://neon.tech/favicon.ico",
		website: "https://neon.tech",
		description: "Serverless Postgres for developers.",
		country: "US",
	},
	{
		id: "spo-007",
		name: "Uploadthing",
		tierId: "tier-silver",
		logo: "https://uploadthing.com/favicon.ico",
		website: "https://uploadthing.com",
		description: "File uploading for modern web apps.",
		country: "US",
	},
	{
		id: "spo-008",
		name: "Inngest",
		tierId: "tier-silver",
		logo: "https://inngest.com/favicon.ico",
		website: "https://inngest.com",
		description: "Durable functions for AI and background jobs.",
		country: "US",
	},
	{
		id: "spo-009",
		name: "Turso",
		tierId: "tier-silver",
		logo: "https://turso.tech/favicon.ico",
		website: "https://turso.tech",
		description: "SQLite for production.",
		country: "US",
	},
	{
		id: "spo-010",
		name: "Crafter Station",
		tierId: "tier-community",
		logo: "https://crafterstation.com/favicon.ico",
		website: "https://crafterstation.com",
		description: "Building Peru's tech ecosystem.",
		country: "PE",
	},
	{
		id: "spo-011",
		name: "HackLab Lima",
		tierId: "tier-community",
		logo: "https://hacklablima.com/favicon.ico",
		website: "https://hacklablima.com",
		description: "Community hackerspace in Lima.",
		country: "PE",
	},
	{
		id: "spo-012",
		name: "DevPerú",
		tierId: "tier-community",
		logo: "https://devperu.org/favicon.ico",
		website: "https://devperu.org",
		description: "The Peruvian developer community.",
		country: "PE",
	},
];

const schedule = [
	{
		id: "ses-001",
		title: "Opening Keynote: The AI-Native Stack",
		description:
			"How the next generation of infrastructure is being rebuilt from the ground up for AI workloads. From embeddings to agents — what changes and what stays the same.",
		day: 1,
		startTime: "09:00",
		endTime: "10:00",
		room: "Main Stage",
		type: "keynote",
		speakerIds: ["spk-001"],
		tags: ["AI", "infrastructure", "keynote"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-002",
		title: "Panel: Open Source AI — Who Owns the Ecosystem?",
		description:
			"A discussion with engineers from Hugging Face, Mozilla, and independent contributors on governance, licensing, and the future of open weights models.",
		day: 1,
		startTime: "10:30",
		endTime: "11:30",
		room: "Main Stage",
		type: "panel",
		speakerIds: ["spk-002", "spk-007", "spk-003"],
		tags: ["open source", "AI", "governance"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-003",
		title: "Workshop: Build an AI Agent with Vercel AI SDK",
		description:
			"Hands-on workshop building a production-ready AI agent from scratch. We'll cover streaming, tool calls, memory, and deployment to the edge.",
		day: 1,
		startTime: "11:45",
		endTime: "13:00",
		room: "Workshop Room A",
		type: "workshop",
		speakerIds: ["spk-001"],
		tags: ["AI SDK", "agents", "workshop"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-004",
		title: "Design Engineering in 2025: When Code IS the Design Tool",
		description:
			"How design engineers are replacing Figma handoffs with live component systems. A deep dive into the Linear design process.",
		day: 1,
		startTime: "14:00",
		endTime: "14:45",
		room: "Track B",
		type: "talk",
		speakerIds: ["spk-004"],
		tags: ["design engineering", "components", "DX"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-005",
		title: "Lightning Talk: Rust in 5 Minutes for JavaScript Developers",
		description:
			"What every JS dev needs to know about Rust without spending 6 months learning it. Practical WASM examples you can ship today.",
		day: 1,
		startTime: "15:00",
		endTime: "15:20",
		room: "Track B",
		type: "lightning",
		speakerIds: ["spk-007"],
		tags: ["Rust", "WebAssembly", "lightning"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-006",
		title: "Edge Networks: From CDN to Compute Fabric",
		description:
			"Cloudflare's journey from cache invalidation to full compute fabric. How Workers, Durable Objects, and Queues change distributed architecture.",
		day: 1,
		startTime: "15:30",
		endTime: "16:15",
		room: "Main Stage",
		type: "talk",
		speakerIds: ["spk-005"],
		tags: ["edge", "distributed systems", "Cloudflare"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-007",
		title: "Day 2 Keynote: Building Startups with AI as Cofounder",
		description:
			"Practical lessons from building Flowdash: what AI actually accelerates, what it doesn't, and how to stay the human who makes decisions.",
		day: 2,
		startTime: "09:00",
		endTime: "10:00",
		room: "Main Stage",
		type: "keynote",
		speakerIds: ["spk-006"],
		tags: ["startups", "AI", "product"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-008",
		title: "Workshop: LLM Evaluation — Beyond Vibes, Into Metrics",
		description:
			"How to build rigorous evals for your AI features. We'll implement model graded evals, human baselines, and automated regression detection.",
		day: 2,
		startTime: "10:30",
		endTime: "12:00",
		room: "Workshop Room A",
		type: "workshop",
		speakerIds: ["spk-002"],
		tags: ["evals", "LLMs", "testing"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-009",
		title: "Multi-Agent Systems: Coordination Without Chaos",
		description:
			"Patterns for building reliable agent swarms. Task decomposition, delegation protocols, and how to debug when five agents disagree.",
		day: 2,
		startTime: "10:30",
		endTime: "11:15",
		room: "Track B",
		type: "talk",
		speakerIds: ["spk-008"],
		tags: ["agents", "AI", "architecture"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-010",
		title: "Lightning Talk: pnpm to Bun in 30 Minutes",
		description:
			"Live migration of a real monorepo. What broke, what got faster, and whether it was worth it.",
		day: 2,
		startTime: "14:00",
		endTime: "14:20",
		room: "Track B",
		type: "lightning",
		speakerIds: ["spk-003"],
		tags: ["Bun", "tooling", "lightning"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-011",
		title: "Panel: LATAM Tech — Building Global Products from Peru, Colombia, Chile",
		description:
			"Founders and engineers from the region discuss remote work, global hiring, and building products that compete worldwide from Lima to Medellín.",
		day: 2,
		startTime: "14:30",
		endTime: "15:30",
		room: "Main Stage",
		type: "panel",
		speakerIds: ["spk-003", "spk-006", "spk-007"],
		tags: ["LATAM", "startups", "remote work"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-012",
		title: "Safety at Scale: What Responsible AI Deployment Looks Like",
		description:
			"From red teaming to constitutional AI — practical techniques for shipping AI features that don't embarrass you at 3am.",
		day: 2,
		startTime: "16:00",
		endTime: "16:45",
		room: "Main Stage",
		type: "talk",
		speakerIds: ["spk-008"],
		tags: ["AI safety", "production", "responsible AI"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-013",
		title: "Closing Keynote: The Next 5 Years of Developer Tools",
		description:
			"A forward look at how AI coding tools, agent frameworks, and infrastructure-as-code are converging into something entirely new.",
		day: 3,
		startTime: "09:00",
		endTime: "10:00",
		room: "Main Stage",
		type: "keynote",
		speakerIds: ["spk-001", "spk-008"],
		tags: ["future", "developer tools", "AI"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-014",
		title: "Hackathon Results & Demo Day",
		description:
			"The 10 finalist teams present their projects live. Judges deliberate in public. Winners announced on stage.",
		day: 3,
		startTime: "10:30",
		endTime: "13:00",
		room: "Main Stage",
		type: "special",
		speakerIds: [],
		tags: ["hackathon", "demos", "community"],
		recordingUrl: null,
		slidesUrl: null,
	},
	{
		id: "ses-015",
		title: "Networking: Closing Mixer",
		description:
			"Wrap up the conference with the community. Meet the speakers, sponsors, and your next cofounder.",
		day: 3,
		startTime: "15:00",
		endTime: "18:00",
		room: "Rooftop Terrace",
		type: "social",
		speakerIds: [],
		tags: ["networking", "community"],
		recordingUrl: null,
		slidesUrl: null,
	},
];

const judges = [
	{
		id: "jdg-001",
		name: "Rodrigo Castaño",
		company: "Sequoia Capital",
		title: "Partner",
		avatar: "https://i.pravatar.cc/150?img=60",
		bio: "Early stage investor focused on dev tools and infrastructure. Former founder.",
		expertise: ["developer tools", "infrastructure", "B2B SaaS"],
		linkedin: "rodrigocastano",
	},
	{
		id: "jdg-002",
		name: "Isabella Vega",
		company: "a16z",
		title: "General Partner",
		avatar: "https://i.pravatar.cc/150?img=49",
		bio: "Leads AI investments at Andreessen Horowitz. Author of the AI Cannon reading list.",
		expertise: ["AI", "machine learning", "enterprise software"],
		linkedin: "isabellavega",
	},
	{
		id: "jdg-003",
		name: "Thomas Osei",
		company: "Y Combinator",
		title: "Group Partner",
		avatar: "https://i.pravatar.cc/150?img=17",
		bio: "YC group partner. Has evaluated 3000+ applications. Loves infrastructure and fintech.",
		expertise: ["startups", "fintech", "infrastructure"],
		linkedin: "thomasosei",
	},
	{
		id: "jdg-004",
		name: "Valentina Ríos",
		company: "Hugging Face",
		title: "ML Research Engineer",
		avatar: "https://i.pravatar.cc/150?img=5",
		bio: "Evaluates AI/ML hackathon submissions with a focus on technical rigor and real-world applicability.",
		expertise: ["machine learning", "NLP", "open source AI"],
		linkedin: "valriosai",
	},
	{
		id: "jdg-005",
		name: "Carlos Mendoza",
		company: "UTEC Ventures",
		title: "Director",
		avatar: "https://i.pravatar.cc/150?img=68",
		bio: "Runs the UTEC startup accelerator in Lima. Focused on tech-for-good in LATAM.",
		expertise: ["LATAM startups", "EdTech", "impact tech"],
		linkedin: "carlosmendozautec",
	},
	{
		id: "jdg-006",
		name: "Mei Zhang",
		company: "Stripe",
		title: "Principal Engineer",
		avatar: "https://i.pravatar.cc/150?img=47",
		bio: "Leads developer experience at Stripe. Evaluates projects for production readiness and API design quality.",
		expertise: ["payments", "API design", "DX"],
		linkedin: "meizhangstripe",
	},
];

const jobs = [
	{
		id: "job-001",
		sponsorId: "spo-001",
		title: "Senior Frontend Engineer",
		company: "Vercel",
		location: "Remote (US/LATAM)",
		type: "full-time",
		seniority: "senior",
		description:
			"Join the team building the Next.js App Router and Vercel deployment UI. TypeScript, React, and edge computing daily.",
		applyUrl: "https://vercel.com/careers",
		tags: ["Next.js", "TypeScript", "React", "Edge"],
		salary: "$160k - $200k",
		posted: "2025-02-15",
	},
	{
		id: "job-002",
		sponsorId: "spo-001",
		title: "Developer Advocate — LATAM",
		company: "Vercel",
		location: "Remote (LATAM)",
		type: "full-time",
		seniority: "mid",
		description:
			"Be the face of Vercel for Spanish-speaking developers. Create content, run workshops, and grow the community.",
		applyUrl: "https://vercel.com/careers",
		tags: ["DevRel", "Content", "Community", "Spanish"],
		salary: "$90k - $120k",
		posted: "2025-02-20",
	},
	{
		id: "job-003",
		sponsorId: "spo-002",
		title: "AI Software Engineer",
		company: "Clerk",
		location: "Remote (US timezone)",
		type: "full-time",
		seniority: "mid",
		description:
			"Build the future of authentication for AI-native apps. Work on MCP servers, evals, CLI tooling, and AI integrations.",
		applyUrl: "https://clerk.com/careers",
		tags: ["AI", "TypeScript", "Bun", "MCP"],
		salary: "$120k - $160k",
		posted: "2025-02-18",
	},
	{
		id: "job-004",
		sponsorId: "spo-003",
		title: "Database Reliability Engineer",
		company: "PlanetScale",
		location: "Remote",
		type: "full-time",
		seniority: "senior",
		description:
			"Keep the world's largest serverless MySQL platform running at 99.999% uptime. Deep MySQL internals knowledge required.",
		applyUrl: "https://planetscale.com/careers",
		tags: ["MySQL", "Go", "reliability", "distributed systems"],
		salary: "$180k - $220k",
		posted: "2025-01-30",
	},
	{
		id: "job-005",
		sponsorId: "spo-004",
		title: "Full Stack Engineer",
		company: "Resend",
		location: "Remote",
		type: "full-time",
		seniority: "mid",
		description:
			"Build email infrastructure that developers love. Work across API, dashboard, and delivery systems.",
		applyUrl: "https://resend.com/careers",
		tags: ["TypeScript", "Node.js", "React", "email"],
		salary: "$110k - $150k",
		posted: "2025-02-10",
	},
	{
		id: "job-006",
		sponsorId: "spo-005",
		title: "Open Source Engineer",
		company: "Trigger.dev",
		location: "Remote",
		type: "full-time",
		seniority: "mid",
		description:
			"Build the best open source background jobs platform. Work in public, ship fast, and engage with the community.",
		applyUrl: "https://trigger.dev/careers",
		tags: ["TypeScript", "open source", "background jobs", "Bun"],
		salary: "$100k - $140k",
		posted: "2025-02-01",
	},
	{
		id: "job-007",
		sponsorId: "spo-006",
		title: "Postgres Infrastructure Engineer",
		company: "Neon",
		location: "Remote (EU/US)",
		type: "full-time",
		seniority: "senior",
		description:
			"Build serverless Postgres at scale. Deep work on storage, branching, and compute separation.",
		applyUrl: "https://neon.tech/careers",
		tags: ["Postgres", "Rust", "Go", "distributed systems"],
		salary: "$160k - $200k",
		posted: "2025-01-25",
	},
	{
		id: "job-008",
		sponsorId: "spo-007",
		title: "Product Engineer",
		company: "Uploadthing",
		location: "Remote",
		type: "full-time",
		seniority: "mid",
		description:
			"Small team, big impact. Help build the file upload infrastructure that hundreds of thousands of apps rely on.",
		applyUrl: "https://uploadthing.com/careers",
		tags: ["TypeScript", "Next.js", "AWS S3", "product"],
		salary: "$100k - $130k",
		posted: "2025-02-12",
	},
	{
		id: "job-009",
		sponsorId: "spo-008",
		title: "Developer Experience Engineer",
		company: "Inngest",
		location: "Remote",
		type: "full-time",
		seniority: "senior",
		description:
			"Own the developer experience for durable functions. SDKs, docs, examples, and the feedback loop with the community.",
		applyUrl: "https://inngest.com/careers",
		tags: ["DX", "TypeScript", "SDKs", "documentation"],
		salary: "$130k - $170k",
		posted: "2025-02-08",
	},
	{
		id: "job-010",
		sponsorId: "spo-002",
		title: "Backend Engineer — Auth Infra",
		company: "Clerk",
		location: "Remote (US timezone)",
		type: "full-time",
		seniority: "senior",
		description:
			"Scale authentication infrastructure to billions of users. Work on session management, tokens, and multi-tenant architecture.",
		applyUrl: "https://clerk.com/careers",
		tags: ["Go", "PostgreSQL", "auth", "infrastructure"],
		salary: "$160k - $200k",
		posted: "2025-02-22",
	},
];

const tracks = [
	{
		id: "trk-001",
		name: "AI & Machine Learning",
		description:
			"Build products powered by LLMs, computer vision, or any AI/ML technology. Judged on real-world impact, technical depth, and responsible AI practices.",
		prizes: [
			{ place: 1, amount: 5000, currency: "USD", label: "First Place" },
			{ place: 2, amount: 2500, currency: "USD", label: "Second Place" },
			{ place: 3, amount: 1000, currency: "USD", label: "Third Place" },
		],
		sponsorId: "spo-001",
		requirements: [
			"Must use at least one AI/ML API or open weights model",
			"Must have a working demo",
			"Teams of 1-4 people",
		],
		color: "#8B5CF6",
	},
	{
		id: "trk-002",
		name: "Open Source for LATAM",
		description:
			"Build or significantly contribute to open source tooling that solves a real problem for Latin American developers or communities.",
		prizes: [
			{ place: 1, amount: 4000, currency: "USD", label: "First Place" },
			{ place: 2, amount: 2000, currency: "USD", label: "Second Place" },
			{ place: 3, amount: 800, currency: "USD", label: "Third Place" },
		],
		sponsorId: "spo-010",
		requirements: [
			"Must be open source (MIT or Apache 2.0)",
			"Must address a specific LATAM developer or community need",
			"Must be documented in Spanish and English",
		],
		color: "#10B981",
	},
	{
		id: "trk-003",
		name: "Developer Tools",
		description:
			"Build tools that make developers more productive. CLIs, extensions, libraries, platforms — if it helps devs ship faster, it qualifies.",
		prizes: [
			{ place: 1, amount: 4500, currency: "USD", label: "First Place" },
			{ place: 2, amount: 2000, currency: "USD", label: "Second Place" },
			{ place: 3, amount: 800, currency: "USD", label: "Third Place" },
		],
		sponsorId: "spo-003",
		requirements: [
			"Must be usable by other developers",
			"Must have installation instructions",
			"Must include at least one working integration test",
		],
		color: "#F59E0B",
	},
];

const teams = [
	{
		id: "team-001",
		name: "Aguila Labs",
		trackId: "trk-001",
		members: [
			{ name: "Diego Quispe", role: "ML Engineer", github: "diegoquispe" },
			{ name: "Sofía Méndez", role: "Full Stack", github: "sofiamendez" },
			{ name: "Juan Carlos Ríos", role: "Product", github: "jcrios" },
		],
		project: {
			name: "Carta Magna",
			description:
				"AI-powered tool that helps Peruvian citizens understand their legal rights in plain Spanish. Uses RAG over the Peruvian Constitution and major legislation.",
			techStack: ["Next.js", "Vercel AI SDK", "Neon", "Clerk"],
			repoUrl: "https://github.com/aguilalabs/carta-magna",
			demoUrl: "https://cartamagna.pe",
			submittedAt: "2025-02-28T23:45:00Z",
		},
		status: "finalist",
		score: 87,
	},
	{
		id: "team-002",
		name: "Cóndor Dev",
		trackId: "trk-002",
		members: [
			{ name: "María Fernanda López", role: "CLI Engineer", github: "mflopez" },
			{ name: "Andrés Torres", role: "Documentation", github: "andrestorres" },
		],
		project: {
			name: "spanishDocs",
			description:
				"CLI tool that auto-generates Spanish documentation from English code comments using LLMs, with support for regional vocabulary (PE/MX/AR/CL/CO).",
			techStack: ["Bun", "TypeScript", "Anthropic SDK", "Biome"],
			repoUrl: "https://github.com/condordev/spanishdocs",
			demoUrl: null,
			submittedAt: "2025-02-28T22:30:00Z",
		},
		status: "finalist",
		score: 84,
	},
	{
		id: "team-003",
		name: "null pointer exception",
		trackId: "trk-003",
		members: [
			{ name: "Pablo Salas", role: "Compiler Engineer", github: "pablosalas" },
			{ name: "Valentina Cruz", role: "DX Engineer", github: "valecruz" },
			{ name: "Nicolás Paredes", role: "Testing", github: "nicoparedes" },
			{ name: "Ana Belén Rios", role: "Docs", github: "anabelenrios" },
		],
		project: {
			name: "typecheck-mcp",
			description:
				"MCP server that exposes the TypeScript compiler API as tools for AI coding assistants, enabling real-time type checking, refactoring, and diagnostics inside any LLM workflow.",
			techStack: ["TypeScript Compiler API", "MCP SDK", "Bun", "Zod"],
			repoUrl: "https://github.com/nullpointerexception/typecheck-mcp",
			demoUrl: "https://typecheck-mcp.dev",
			submittedAt: "2025-02-28T21:00:00Z",
		},
		status: "finalist",
		score: 91,
	},
	{
		id: "team-004",
		name: "Huacas de Código",
		trackId: "trk-001",
		members: [
			{ name: "Renzo Mamani", role: "ML Engineer", github: "renzomamani" },
			{ name: "Claudia Heredia", role: "Backend", github: "claudiaheredia" },
		],
		project: {
			name: "AgroIA",
			description:
				"Mobile-first app using computer vision to identify crop diseases in Peruvian highland agriculture. Works offline, built for low-connectivity environments.",
			techStack: ["React Native", "ONNX Runtime", "FastAPI", "PostgreSQL"],
			repoUrl: "https://github.com/huacasdecodigo/agroia",
			demoUrl: "https://agroia.pe",
			submittedAt: "2025-02-28T23:59:00Z",
		},
		status: "submitted",
		score: 79,
	},
	{
		id: "team-005",
		name: "Sipán Stack",
		trackId: "trk-003",
		members: [
			{ name: "Gabriela Pacheco", role: "Platform Engineer", github: "gabipacheco" },
			{ name: "Luis Enrique Vásquez", role: "CLI", github: "levasquez" },
			{ name: "Carmen Rosa Flores", role: "UX", github: "crflores" },
		],
		project: {
			name: "deploya",
			description:
				"Zero-config deployment CLI for LATAM developers that abstracts Vercel, Railway, and Render behind a single unified interface with Spanish-language error messages.",
			techStack: ["Bun", "TypeScript", "Ink (React for CLIs)", "Commander"],
			repoUrl: "https://github.com/sipanstack/deploya",
			demoUrl: null,
			submittedAt: "2025-02-28T20:15:00Z",
		},
		status: "submitted",
		score: 76,
	},
];

const output = {
	speakers,
	sponsorTiers,
	sponsors,
	schedule,
	judges,
	jobs,
	tracks,
	teams,
};

process.stdout.write(JSON.stringify(output, null, 2));
